<a href="https://colab.research.google.com/github/ksimhadr/learn/blob/master/_Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Linear regression
X = np.array([[1, 1], [1, 2], [1, 3], [1, 4]])
y = np.array([2,4,6,8])

# Quadratic regression
X_quad = np.array([[1, 1, 1**2], [1, 2, 2**2], [1, 3, 3**2], [1, 4, 4**2]])
w_quad = np.linalg.inv(X_quad.T @ X_quad) @ (X_quad.T @ y)

w_quad


array([-2.84217094e-14,  2.00000000e+00,  1.44328993e-14])

In [6]:
# prompt: understanding python keywords - assert break continue except false finally global lambda none nonlocal raise pass try yield

# assert: Used for debugging, raises an AssertionError if the condition is false.
def divide(x, y):
  assert y != 0, "Division by zero not allowed!"
  return x / y

divide(10, 1)

# break: Exits the current loop.
for i in range(10):
  if i == 2:
    break
  print(i)

# continue: Skips the rest of the current iteration and goes to the next.
for i in range(10):
  if i % 2 == 0:
    continue
  print(i)

# except: Handles exceptions that occur within a try block.
try:
  result = 10 / 0
except ZeroDivisionError:
  print("Division by zero using try and except!")

# false: Boolean value representing the absence of truth.
if False:
  print("This won't print.")

# finally: Executes code regardless of whether an exception occurs.
try:
  result = 10 / 0
except ZeroDivisionError:
  print("Division by zero in exception!")
finally:
  print("This will always print using finally.")

# global: Used to access and modify global variables within a function.
global_var = 10
def modify_global():
  global global_var
  global_var = 200

modify_global()
print(global_var)

# lambda: Creates anonymous functions.
square = lambda x: x * x
square(5)

# None: Represents the absence of a value.
empty_value = None
if empty_value is None:
  print("This is an empty value.")


# nonlocal: Used to access and modify variables in enclosing scopes.
def outer_func():
  x = 10
  def inner_func():
    nonlocal x
    x = 20
  inner_func()
  print(x)

outer_func()

# raise: Raises an exception.
def check_age(age):
  if age < 0:
    raise ValueError("Age cannot be negative!")

# pass: Placeholder statement, does nothing.
def empty_function():
  pass

# try: Used to enclose code that might raise exceptions.
try:
  result = 10 / 0
except ZeroDivisionError:
  print("Division by zero!")

# yield: Used in generator functions to produce a sequence of values.
def generate_numbers(n):
  for i in range(n):
    yield i

generate_numbers(5)


0
1
1
3
5
7
9
Division by zero using try and except!
Division by zero in exception!
This will always print using finally.
200
This is an empty value.
20
Division by zero!


<generator object generate_numbers at 0x7d109092d070>

In [7]:
# prompt: how to use yield

def generate_even_numbers(n):
  """Generates even numbers up to n."""
  for i in range(2, n + 1, 2):
    yield i

# Create a generator object
even_nums = generate_even_numbers(10)

# Iterate over the generator to get values
for num in even_nums:
  print(num)


2
4
6
8
10


In [8]:
# prompt: slicing

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Get the first 3 elements
first_three = my_list[:3]
print(first_three)  # Output: [1, 2, 3]

# Get elements from index 2 to the end
from_index_2 = my_list[2:]
print(from_index_2)  # Output: [3, 4, 5, 6, 7, 8, 9, 10]

# Get elements from index 3 to 7 (exclusive)
slice_3_to_7 = my_list[3:7]
print(slice_3_to_7)  # Output: [4, 5, 6, 7]

# Get every other element
every_other = my_list[::2]
print(every_other)  # Output: [1, 3, 5, 7, 9]

# Reverse the list
reversed_list = my_list[::-1]
print(reversed_list)  # Output: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


[1, 2, 3]
[3, 4, 5, 6, 7, 8, 9, 10]
[4, 5, 6, 7]
[1, 3, 5, 7, 9]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [12]:
# prompt: difference between set tuple list dictionaries

# Lists
# - Ordered collections of items.
# - Mutable (can be changed after creation).
# - Allows duplicate elements.
my_list = [1, 2, 3, 2, 4]
print(my_list)  # Output: [1, 2, 3, 2, 4]

# Tuples
# - Ordered collections of items.
# - Immutable (cannot be changed after creation).
# - Allows duplicate elements.
my_tuple = (1, 2, 3, 2, 4)
print(my_tuple)  # Output: (1, 2, 3, 2, 4)

# Sets
# - Unordered collections of unique items.
# - Mutable (can be changed after creation).
# - Does not allow duplicate elements.
my_set = {1, 2, 3, 2, 4}
print(my_set)  # Output: {1, 2, 3, 4}

# Dictionaries
# - Store data in key-value pairs.
# - Keys must be unique.
# - Mutable (can be changed after creation).
my_dict = {"name": "Alice", "age": 30, "city": "New York"}
print(my_dict)  # Output: {'name': 'Alice', 'age': 30, 'city': 'New York'}


[1, 2, 3, 2, 4]
(1, 2, 3, 2, 4)
{1, 2, 3, 4}
{'name': 'Alice', 'age': 30, 'city': 'New York'}


In [19]:
# prompt: numpy arange mean median

import numpy as np

# Create an array using arange
arr = np.arange(0, 5)  # Creates an array from 1 to 10

# Calculate the mean
#mean = np.mean(arr)
#print("Mean:", mean)

# Calculate the median
median = np.median(arr)
print("Median:", median)


Median: 2.0


In [27]:
# prompt: arange and reshape

import numpy as np

# Create an array using arange and reshape
arr = np.array([np.arange(50).reshape(1, 50),np.arange(50).reshape(1, 50)])
arr.shape
#arr.reshape(2,50)
#print(arr)


(2, 1, 50)

In [28]:
# prompt: using numpy methods with different examples

import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Basic operations
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

# Reshaping
arr_2d = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print("\nReshaped Array:\n", arr_2d)

# Indexing and slicing
print("\nFirst element:", arr_2d[0, 0])
print("First row:", arr_2d[0, :])
print("First column:", arr_2d[:, 0])

# Mathematical functions
print("\nSine of array:", np.sin(arr))
print("Cosine of array:", np.cos(arr))
print("Exponential of array:", np.exp(arr))
print("Logarithm of array:", np.log(arr))

# Linear algebra
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.solve(a, b)
print("\nSolution to linear equations:", x)

# Random number generation
random_arr = np.random.rand(5)
print("\nRandom array:", random_arr)


Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0

Reshaped Array:
 [[1 2 3]
 [4 5 6]]

First element: 1
First row: [1 2 3]
First column: [1 4]

Sine of array: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine of array: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Exponential of array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm of array: [0.         0.69314718 1.09861229 1.38629436 1.60943791]

Solution to linear equations: [-4.   4.5]

Random array: [0.3149014  0.44235135 0.10816218 0.87848997 0.80384955]


In [31]:
import numpy as np
y = [["apple", "banana", "cherry"], 0, 12, ["grapes", 'citroud']]   #nested list
print(y)
print(type(y))

[['apple', 'banana', 'cherry'], 0, 12, ['grapes', 'citroud']]
<class 'list'>


In [32]:
# prompt: in is any

if any(isinstance(item, list) for item in y):
  print("List found in y")
else:
  print("No list found in y")


List found in y


In [43]:
#in operator checks the object membership
x = [{12},12, 12]
y = [1, 12, 13, 0, -12, 9, {12}]
print(x in y)

#is operator checks for objects identity
print(x is y)


False
False


In [48]:
#  Define a function() that takes two lists
def overlapping(list1, list2):

    c = 0
    d = 0
    for i in list1:
        c += 1
    for i in list2:
        d += 1
    for i in range(0, c):
        for j in range(0, d):
            print(list1[i], list2[j])
            if(list1[i] == list2[j]):
                return 1
    return 0


list1 = [1, 2, 3, 4, 5]
list2 = [6, 1, 8, 9]
if(overlapping(list1, list2)):
    print("overlapping")
else:
    print("not overlapping")


1 6
1 1
overlapping


In [51]:
lst1 = [1, 2, 3]
lst2 = [1, 2, 3]

if lst1 is lst2: #compares the memory locations of two objects
    print("lst1 and lst2 are the same object")
elif (lst1 == lst2): #compares two values
    #print("lst1 and lst2 are same objects")
    print("lst1 and lst2 have the same values")
else:
    print("lst1 and lst2 are different objects")


lst1 and lst2 have the same values


In [52]:
#container/data-structure can be list, tuple, set, dict
x = 61
y = [1, 3, 6, -3, 11]

# write expression "x in y" using 'is' keyword
any( x is ele or x == ele for ele in y )

False

In [55]:
# prompt: length of list with different examples nested lists and 2D lists

# Simple list
my_list = [1, 2, 3, 4, 5]
print(len(my_list))  # Output: 5

# Nested list
nested_list = [[1, 2], [3, 4], [5, 6], {}]
print(len(nested_list))  # Output: 3

# 2D list
two_d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(len(two_d_list))  # Output: 3


5
4
3


In [56]:
# prompt: callable function with different examples

# Check if a function is callable
def my_function():
  """This is a sample function."""
  print("Hello from my_function!")

print(callable(my_function))  # Output: True
print(callable(10))  # Output: False
print(callable("hello"))  # Output: False
print(callable([1, 2, 3]))  # Output: False
print(callable(my_function()))  # Output: False (because my_function() returns None)


True
False
False
False
Hello from my_function!
False


In [57]:
# prompt: repr and str difference

class MyClass:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"MyClass(name={self.name}, age={self.age})"

    def __repr__(self):
        return f"MyClass('{self.name}', {self.age})"

obj = MyClass("Alice", 30)

print(str(obj))  # Output: MyClass(name=Alice, age=30)
print(repr(obj))  # Output: MyClass('Alice', 30)


MyClass(name=Alice, age=30)
MyClass('Alice', 30)


In [58]:
line = "I\'ll come by then."
eline = ""
for i in line:
	eline += chr(ord(i)+3)
print(eline)


L*oo#frph#e|#wkhq1


In [62]:
# prompt: map lambda filter examples

# Map: Apply a function to each element of an iterable.
numbers = [1, 2, 3, 4, 5]
squaredNum = list((lambda x: x * x, numbers))
print(squaredNum)  # Output: [1, 4, 9, 16, 25]
squared_numbers = list(map(lambda x: x * x, numbers))
print(squared_numbers)  # Output: [1, 4, 9, 16, 25]

# Filter: Create a new iterable with elements that satisfy a condition.
numbers = [1, 2, 3, 4, 5]
even_numbers = list(filter(lambda x: x % 2 == 0, squared_numbers))
print(even_numbers)  # Output: [2, 4]


[<function <lambda> at 0x7d10749180d0>, [1, 2, 3, 4, 5]]
[1, 4, 9, 16, 25]
[4, 16]


In [63]:
param = {'w1': 0.34, 'w2':0.002, 'b1':2, 'b2':2.2}
param.items()

dict_items([('w1', 0.34), ('w2', 0.002), ('b1', 2), ('b2', 2.2)])

In [64]:
for key, value in param.items():
    print(key, value)

w1 0.34
w2 0.002
b1 2
b2 2.2


In [67]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(a1D)
print(a2D)
print(a3D)
np.shape(a1D), np.shape(a2D), np.shape(a3D)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


((4,), (2, 2), (2, 2, 2))

In [68]:
# prompt: examples oops, inheritance

class Animal:
  """A class representing an animal."""

  def __init__(self, name, species):
    """Initialize the Animal object."""
    self.name = name
    self.species = species

  def make_sound(self):
    """Make a generic animal sound."""
    print("Generic animal sound")

  def move(self):
    """Move the animal."""
    print("Animal is moving")


class Dog(Animal):
  """A class representing a dog."""

  def __init__(self, name, breed):
    """Initialize the Dog object."""
    super().__init__(name, species="Dog")
    self.breed = breed

  def make_sound(self):
    """Make a dog sound."""
    print("Woof!")

  def fetch(self):
    """Fetch a toy."""
    print("Fetching...")


class Cat(Animal):
  """A class representing a cat."""

  def __init__(self, name, color):
    """Initialize the Cat object."""
    super().__init__(name, species="Cat")
    self.color = color

  def make_sound(self):
    """Make a cat sound."""
    print("Meow!")

  def scratch(self):
    """Scratch something."""
    print("Scratching...")


# Create instances of the classes
my_dog = Dog("Buddy", "Golden Retriever")
my_cat = Cat("Whiskers", "Gray")

# Access attributes and methods
print(my_dog.name)  # Output: Buddy
print(my_dog.breed)  # Output: Golden Retriever
my_dog.make_sound()  # Output: Woof!
my_dog.fetch()  # Output: Fetching...

print(my_cat.name)  # Output: Whiskers
print(my_cat.color)  # Output: Gray
my_cat.make_sound()  # Output: Meow!
my_cat.scratch()  # Output: Scratching...


Buddy
Golden Retriever
Woof!
Fetching...
Whiskers
Gray
Meow!
Scratching...


In [69]:
normal_set = set(["a", "b","c"])

print("Normal Set")
print(normal_set)

# A frozen set
frozen_set = frozenset(["e", "f", "g"])

print("\nFrozen Set")
print(frozen_set)



Normal Set
{'b', 'c', 'a'}

Frozen Set
frozenset({'g', 'e', 'f'})


In [71]:
# prompt: frozenset bytearray stacks queues

# Frozenset: An immutable version of a set.
my_frozenset = frozenset([1, 2, 0])
print(my_frozenset)  # Output: frozenset({1, 2, 3})

# Bytearray: A mutable sequence of bytes.
my_bytearray = bytearray([65, 66, 67])  # ASCII values for 'A', 'B', 'C'
print(my_bytearray)  # Output: bytearray(b'ABC')

# Stacks: LIFO (Last-In, First-Out) data structure.
# Using a list as a stack
my_stack = []
my_stack.append(1)
my_stack.append(2)
my_stack.append(3)
print(my_stack.pop())  # Output: 3
print(my_stack.pop())  # Output: 2

# Queues: FIFO (First-In, First-Out) data structure.
from collections import deque
my_queue = deque([1, 2, 3])
my_queue.append(4)
print(my_queue.popleft())  # Output: 1


frozenset({0, 1, 2})
bytearray(b'ABC')
3
2
1


In [72]:
from collections import UserList

# Creating a custom list class by inheriting from UserList
class MyList(UserList):
    # Adding a custom method
    def square_elements(self):
        self.data = [x ** 2 for x in self.data]

# Creating an instance of the custom list
my_custom_list = MyList([1, 2, 3, 4, 5])

# Displaying the original list
print("Original List:", my_custom_list)

# Using the custom method to square elements
my_custom_list.square_elements()
print("List after Squaring Elements:", my_custom_list)

# Accessing elements using standard list methods
element_at_index_2 = my_custom_list[2]
print("Element at Index 2:", element_at_index_2)

# Modifying an element
my_custom_list[1] = 10
print("Modified List:", my_custom_list)

Original List: [1, 2, 3, 4, 5]
List after Squaring Elements: [1, 4, 9, 16, 25]
Element at Index 2: 9
Modified List: [1, 10, 9, 16, 25]


In [73]:
# prompt: ordereddict deque defaultdict chainmap tabulardata

from collections import OrderedDict, deque, defaultdict, ChainMap
from tabulate import tabulate

# OrderedDict: A dictionary that remembers the order of insertion.
ordered_dict = OrderedDict()
ordered_dict['a'] = 1
ordered_dict['b'] = 2
ordered_dict['c'] = 3
print("OrderedDict:", ordered_dict)

# deque: A double-ended queue, provides fast append and pop operations from both ends.
my_deque = deque([1, 2, 3])
my_deque.append(4)
my_deque.appendleft(0)
print("Deque:", my_deque)

# defaultdict: A dictionary that automatically creates default values for missing keys.
default_dict = defaultdict(int)
default_dict['a'] = 1
print("Defaultdict:", default_dict['a'], default_dict['b'])

# ChainMap: Combines multiple dictionaries into a single view.
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
combined_dict = ChainMap(dict1, dict2)
print("ChainMap:", combined_dict)

# tabulate: Formats data into a tabular form.
data = [["Name", "Age", "City"], ["Alice", 30, "New York"], ["Bob", 25, "London"]]
print("Tabular Data:\n", tabulate(data, headers="firstrow", tablefmt="grid"))


OrderedDict: OrderedDict([('a', 1), ('b', 2), ('c', 3)])
Deque: deque([0, 1, 2, 3, 4])
Defaultdict: 1 0
ChainMap: ChainMap({'a': 1, 'b': 2}, {'c': 3, 'd': 4})
Tabular Data:
 +--------+-------+----------+
| Name   |   Age | City     |
+========+=======+==========+
| Alice  |    30 | New York |
+--------+-------+----------+
| Bob    |    25 | London   |
+--------+-------+----------+


In [74]:
from collections import OrderedDict

# Creating an OrderedDict
ordered_dict = OrderedDict()

# Adding key-value pairs
ordered_dict['one'] = 1
ordered_dict['two'] = 2
ordered_dict['three'] = 3

# Displaying the original order
print("Original Order:", ordered_dict)

# Moving 'two' to the end
ordered_dict.move_to_end('two')

# Displaying the updated order
print("After Moving 'two' to End:", ordered_dict)

Original Order: OrderedDict([('one', 1), ('two', 2), ('three', 3)])
After Moving 'two' to End: OrderedDict([('one', 1), ('three', 3), ('two', 2)])


In [75]:
#deque
from collections import deque

# Initializing a deque
my_deque = deque([1, 2, 3, 4, 5])

# Appending elements at the right end
my_deque.append(6)
my_deque.append(7)

# Displaying the deque
print("Original Deque:", my_deque)

# Popping element from the right end
popped_right = my_deque.pop()
print("Popped from Right:", popped_right)
print("Updated Deque:", my_deque)

# Appending elements at the left end
my_deque.appendleft(0)
my_deque.appendleft(-1)

# Displaying the updated deque
print("Updated Deque after Appending Left:", my_deque)

# Popping element from the left end
popped_left = my_deque.popleft()
print("Popped from Left:", popped_left)
print("Final Deque:", my_deque)


Original Deque: deque([1, 2, 3, 4, 5, 6, 7])
Popped from Right: 7
Updated Deque: deque([1, 2, 3, 4, 5, 6])
Updated Deque after Appending Left: deque([-1, 0, 1, 2, 3, 4, 5, 6])
Popped from Left: -1
Final Deque: deque([0, 1, 2, 3, 4, 5, 6])


In [76]:
#namedtuple
from collections import namedtuple

# Creating a namedtuple class
Person = namedtuple('Person', ['name', 'age', 'gender'])

# Creating instances of the namedtuple
person1 = Person(name='Alice', age=25, gender='Female')
person2 = Person(name='Bob', age=30, gender='Male')

# Accessing fields using names
print("Person 1:", person1.name, person1.age, person1.gender)
print("Person 2:", person2.name, person2.age, person2.gender)

Person 1: Alice 25 Female
Person 2: Bob 30 Male


In [77]:
from collections import defaultdict

# Initializing defaultdict with int factory function
fruit_counter = defaultdict(int)

# Counting occurrences of fruits
fruits = ['apple', 'orange', 'banana', 'apple', 'banana', 'grape']

for fruit in fruits:
    fruit_counter[fruit] += 1

# Displaying the defaultdict
print("Fruit Counter:", dict(fruit_counter))

# Accessing a key with default value
kiwi_count = fruit_counter['kiwi']
print("Count of Kiwi (Default Value):", kiwi_count)

# Initializing defaultdict with list factory function
fruit_groups = defaultdict(list)

# Grouping fruits by their first letter
for fruit in fruits:
    fruit_groups[fruit[0]].append(fruit)

# Displaying the grouped defaultdict
print("Fruit Groups:", dict(fruit_groups))

Fruit Counter: {'apple': 2, 'orange': 1, 'banana': 2, 'grape': 1}
Count of Kiwi (Default Value): 0
Fruit Groups: {'a': ['apple', 'apple'], 'o': ['orange'], 'b': ['banana', 'banana'], 'g': ['grape']}


In [78]:
from collections import Counter

# Creating a Counter from a list
fruit_list = ['apple', 'orange', 'banana', 'apple', 'banana', 'grape']
fruit_counter = Counter(fruit_list)

# Displaying the Counter
print("Fruit Counter:", fruit_counter)

# Counting occurrences of a specific element
apple_count = fruit_counter['apple']
print("Count of Apples:", apple_count)

# Displaying the most common elements
most_common = fruit_counter.most_common(1)
print("Most Common Elements:", most_common)

# Adding new data to the Counter
more_fruits = ['apple', 'kiwi', 'banana']
fruit_counter.update(more_fruits)

# Displaying the updated Counter
print("Updated Fruit Counter:", fruit_counter)

Fruit Counter: Counter({'apple': 2, 'banana': 2, 'orange': 1, 'grape': 1})
Count of Apples: 2
Most Common Elements: [('apple', 2)]
Updated Fruit Counter: Counter({'apple': 3, 'banana': 3, 'orange': 1, 'grape': 1, 'kiwi': 1})


In [83]:
from collections import ChainMap

#Creating two dictionaries
dict1 = {'apple': 1, 'banana': 2}
dict2 = {'banana': 3, 'orange': 4}

#Creating a ChainMap
chain = ChainMap(dict1, dict2)

#Displaying
print("ChainMap:", chain)

#Accessing values
print("Value for 'apple':", chain['apple'])
print("Value for 'banana':", chain['banana'])
print("Value for 'orange':", chain['orange'])

#Adding new dictionary to chain map
dict3 = {'kiwi': 5}
chain_with_kiwi = chain.new_child(dict3)

#Displaying
print("ChainMap with Kiwi:", chain_with_kiwi)

#Updating values in original dictionaries
dict1['banana'] = 10
dict2['banana'] = 15

#Displaying
print("Updated ChainMap:", chain_with_kiwi)

ChainMap: ChainMap({'apple': 1, 'banana': 2}, {'banana': 3, 'orange': 4})
Value for 'apple': 1
Value for 'banana': 2
Value for 'orange': 4
ChainMap with Kiwi: ChainMap({'kiwi': 5}, {'apple': 1, 'banana': 2}, {'banana': 3, 'orange': 4})
Updated ChainMap: ChainMap({'kiwi': 5}, {'apple': 1, 'banana': 10}, {'banana': 15, 'orange': 4})
