<a href="https://colab.research.google.com/github/ksimhadr/learn/blob/master/PY4AIML_Assignment_03_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercises on NumPy


##Numerical python for solving science and engineering problems

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1.2, 21, 31], [4, 5, 6]])
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)

(3,)
(2, 3)
int64
float64


##NumPy Slicing [startindex:endindex:stepsize]

In [4]:
a = np.array(np.arange(12).reshape(3, 4))
print(a)
print(a[1,0::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 6]


##Replace all odd numbers in the given array with -1

In [6]:
import numpy as np
a = np.array(np.random.randint(0,10,10,int))
print(a)
a[a%2==1] = -1
print(a)

[5 8 9 8 5 8 7 8 2 6]
[-1  8 -1  8 -1  8 -1  8  2  6]


##Convert a 1-D array into a 2-D array with 3 rows

In [14]:
import numpy as np
a = np.array(np.arange(12))
print(a)
b = a.reshape(3,4)
print(b)
b = b + 202
print(b)
b.ndim
b.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[202 203 204 205]
 [206 207 208 209]
 [210 211 212 213]]


(3, 4)

##Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)

In [15]:
import numpy as np
a = np.array(np.random.randint(30,40,10))
print(a)

[31 34 34 38 33 30 36 36 30 30]


##Find the positions of:

*  elements in x where its value is more than its corresponding element in y, and

*  elements in x where its value is equals to its corresponding
element in y.


In [16]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x>y))
print(np.where(x==y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)
